10_laravel_tdd/project/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/disk/{path}/download_link', 'App\Http\Controllers\FileController@link_download')->name("disk.link_download");
Route::get('/disk/{disk}/download', 'App\Http\Controllers\FileController@download')->name("disk.download")->middleware('auth');
Route::get('/disk/{disk}/link', 'App\Http\Controllers\FileController@link')->middleware('auth')->name("disk.link");
Route::get('/disk/upload', 'App\Http\Controllers\FileController@upload')->middleware('auth')->name("disk.upload");
Route::get('/disk/shared', 'App\Http\Controllers\FileController@shared')->middleware('auth')->name("disk.shared");
Route::get('/disk/{disk}/delete','App\Http\Controllers\FileController@delete')->middleware('auth')->name('disk.delete');
Route::get('/disk/{disk}/soft_delete','App\Http\Controllers\FileController@soft_delete')->middleware('auth')->name('disk.soft_delete');
Route::get('/disk/notifications', 'App\Http\Controllers\FileController@notifications')->middleware('auth')->name("disk.notifications");

Route::get('/disk/{disk}/share', 'App\Http\Controllers\FileController@share')->middleware('auth')->name("disk.share");


Route::post('/disk/{disk}/share', 'App\Http\Controllers\FileController@share_my_file')->middleware('auth')->name("disk.share");

Route::resource('/disk', App\Http\Controllers\FileController::class)->middleware('auth');
Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/logout', function () {
    Auth::guard()->logout();
    return view('welcome');
});

require __DIR__.'/auth.php';

10_laravel_tdd/project/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

10_laravel_tdd/project/resources/views/disk/download.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Download link') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    Here is your download link!<br/>
                    <label for="link">Copy and share:</label><br>
                    <input type="text" id="link" name="link" value={{$path}}>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

10_laravel_tdd/project/resources/views/disk/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Your files') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    @if($files==null)
                    <p class="p-6">No files yet!</p>
                @else
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                        <tr>
                            <th scope="col"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Name
                            </th>
                            <th scope="col"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Size
                            </th>
                        </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200">
                        @foreach($files as $file)
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm text-gray-500">{{ $file->file_name }}</div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm text-gray-900">{{ $file->size }} bytes</div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="{{ route('disk.download', $file->id) }}" class="text-indigo-600 hover:text-indigo-900">Download</a>
                                    <br>
                                    <a href="{{ route('disk.link', $file->id) }}" class="text-indigo-600 hover:text-indigo-900">Share download link</a>
                                    <br>
                                    @if($shared_flag==false)
                                    <form method="post">
                                        <a href="{{ route('disk.delete', $file->id) }}" class="text-indigo-600 hover:text-indigo-900" >Delete</a>
                                        <br>
                                        @else
                                           <a href="{{ route('disk.soft_delete', $file->id) }}" class="text-indigo-600 hover:text-indigo-900" >Delete</a>
                                        </form>
                                     @endif
                                    <form method="post">
                                        <a href="{{ route('disk.share', $file->id) }}" class="text-indigo-600 hover:text-indigo-900" >Share</a>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                @endif

                @if($shared_flag==false)
                <div class="flex items-center justify-end mt-4 px-4 pb-5">
                    <form method="get" action="/disk/upload">
                        <x-button class="ml-4">
                            {{ __('Upload new file!') }}
                        </x-button>
                    </form>
                </div>
                    @endif
            </div>
        </div>
    </div>
</x-app-layout>

10_laravel_tdd/project/resources/views/disk/notifications.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Notifications') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    @foreach($notifications as $notification)
                        <li>
                            @if($notification->type == 'App\Notifications\ShareNotification')
                                User with email: {{$notification->data['email']}} shared you a file! <br>
                                File name: {{$notification->data['file_name']}}
                            @endif
                        </li>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

10_laravel_tdd/project/resources/views/disk/share.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __("Share") }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />
                    <form method="post"  enctype="multipart/form-data">
                        @csrf
                        <div>
                            <x-label for="email" :value="__('User email:')" /><br/>
                            <x-input id="email" class="block mt-1 w-full" type="text" name="email" :value="old('email')" autofocus />
                        </div>
                        <div class="flex items-center justify-end mt-4">
                            <x-button class="ml-4">
                                {{ __('Share') }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

10_laravel_tdd/project/resources/views/disk/upload.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Upload') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />
                    <form method="post" action="{{ route('disk.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div>
                            <x-label for="file" :value="__('Upload your file:')" /><br/>
                            <x-input id="file" class="block mt-1 w-full" type="file" name="file" :value="old('file')" autofocus />
                        </div>
                        <div class="flex items-center justify-end mt-4">
                            <x-button class="ml-4">
                                {{ __('Go!') }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>